-- MySQL Script generated by MySQL Workbench
-- 04/13/16 16:52:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema srozic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema srozic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `srozic` DEFAULT CHARACTER SET utf8 ;
USE `srozic` ;

-- -----------------------------------------------------
-- Table `srozic`.`osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srozic`.`osoba` (
  `id` INT(11) NOT NULL COMMENT '',
  `ime` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `prezime` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `srozic`.`podaci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srozic`.`podaci` (
  `id` INT(11) NOT NULL COMMENT '',
  `car` INT(11) NULL DEFAULT NULL COMMENT '',
  `moto` INT(11) NULL DEFAULT NULL COMMENT '',
  `bus` INT(11) NULL DEFAULT NULL COMMENT '',
  `lgv` INT(11) NULL DEFAULT NULL COMMENT '',
  `hgv` INT(11) NULL DEFAULT NULL COMMENT '',
  `bike` INT(11) NULL DEFAULT NULL COMMENT '',
  `linija` INT(11) NULL DEFAULT NULL COMMENT '',
  `datum` DATE NULL DEFAULT NULL COMMENT '',
  `lokacija` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `osobafk` INT(11) NULL DEFAULT NULL COMMENT '',
  `interal` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `osobaFK_idx` (`osobafk` ASC)  COMMENT '',
  CONSTRAINT `osobaFK`
    FOREIGN KEY (`osobafk`)
    REFERENCES `srozic`.`osoba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
